[project]
name = "school-map-au"
version = "0.1.0"
description = ""
authors = [
    {name = "Jay Jiang",email = "48189996+crankswagon@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit (>=1.45.1,<2.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "pydeck (>=0.9.1,<0.10.0)",
    "scikit-learn (>=1.7.0,<2.0.0)",
    "geopandas (>=1.1.0,<2.0.0)",
    "plotly (>=6.1.2,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"
